// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xooxsrtygzjmwdkizzqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb3hzcnR5Z3pqbXdka2l6enFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjE5NTksImV4cCI6MjA3MDA5Nzk1OX0.AzPjyS2GFjev5P9a3ejgv9YEvbMNWOLXlpRVRb1gqxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});